name: Core Tenant Artifact action CI

on:
  push:
    branches:
      - master
      - feature/*

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSION: v2

jobs:
  release-tenant-artifact-action:
    name: Checkout main and tenant-artifact action repositories, release action
    runs-on: ubuntu-20.04
    steps:
      - name: Initialize environment variables
        run: |
          GIT_BRANCH="${GITHUB_REF#refs/heads/}"

          if [[ "master" != "${GIT_BRANCH}" ]]; then
            VERSION="${VERSION}-develop"
          fi

          echo "GIT_BRANCH=${GIT_BRANCH}" >> ${GITHUB_ENV}
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}

      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Release action
        run: |
          ./release-service.sh ${{ env.VERSION }} ${{ env.GIT_BRANCH }} ${{ env.GITHUB_SHA }} ""
